### ISSUE TITLE
Error with Jest

### ISSUE THREAD

**Issue by lalo73** [kristerkari/react-native-less-transformer#1]
Hi!

I have an error when I try to run my Jest tests.
I've followed the instructions and everything works fine for development.

But when I run my tests, I have this error:

```
tests/views/Login.test.js
  ● Test suite failed to run

    /app/styles/less/common.less:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@backgroundColor: #fff;
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      1 | import {StyleSheet} from "react-native";
    > 2 | import extraStyles from "./less/common.less";
        | ^
      3 | 
      4 | export const styles = StyleSheet.create({});
      5 | 

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (app/styles/common.js:2:1)
      at Object.<anonymous> (app/views/Login.js:5:1)

```

I tried to configure Jest in my `package.json`:

```
"jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "less",
      "js"
    ],
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/babel-jest",
      "\\.(less)$": "<rootDir>/node_modules/react-native-less-transformer"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(less|js)$",
    "testPathIgnorePatterns": [
      "\\.snap$",
      "<rootDir>/node_modules/"
    ],
    "cacheDirectory": ".jest/cache"
  },
```

But it raised another error:

```
TypeError: Jest: a transform must export a `process` function.

      1 | import {StyleSheet} from "react-native";
    > 2 | import extraStyles from "./less/common.less";
        |               ^
      3 | 
      4 | export const styles = StyleSheet.create({});
      5 | 

      at ScriptTransformer._getTransformer (node_modules/jest-runtime/build/script_transformer.js:236:15)
      at Object.<anonymous> (app/styles/common.js:2:15)
```

My dependencies are:

```
"dependencies": {
    "axios": "^0.18.0",
    "prop-types": "^15.6.2",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-config": "^0.11.5",
    "react-navigation": "^2.10.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0"
  },
"devDependencies": {
    "babel-eslint": "^8.2.6",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "eslint": "^5.2.0",
    "eslint-plugin-jest": "^21.18.0",
    "eslint-plugin-react": "^7.10.0",
    "faker": "^4.1.0",
    "jest": "^23.4.2",
    "jest-react-native": "^18.0.0",
    "jscpd": "^0.6.22",
    "less": "^3.8.1",
    "react-native-cli": "^2.0.1",
    "react-native-less-transformer": "^1.1.2",
    "react-test-renderer": "16.3.1"
  },
```

- Is there a way of using this library with Jest?

**Comment by kristerkari** [comment]
This is actually something that is documented on Jest's website:
https://jestjs.io/docs/en/webpack#mocking-css-modules

**Comment by lalo73** [comment]
Oh yeah, you're right. It works now.
Sorry about the noob question.
Fell free to close the issue.

Thanks

**Comment by kristerkari** [comment]
I'm happy that you got it working. Let me know if you run into any additional issues or find bugs 👍
